### PR TITLE
Refactor gui_spec.rb to solve issue #29

### PR DESCRIPTION
**Pull request by abinoam**
I'm beginner on RSpec. 
So don't merge it before discussing the issue with someone more experienced than me.
I just made this pull request to "show" this code and put it on discussion.

The reasoning of this pull request of mine is:
- I thought the issue was overcomplicated using doubles (mocks/stubs)
- As a beginner on RSpec I thought Mocks/Stubs were more useful when "faking" something that you can't instantiate at test time or at least is too long (execution time) or unreliable as database access, file writings, internet comunications. So I couldn't see the point in "doubling" things that you should instantiate (at almost the same execution time cost as "doubling" it).
- Perhaps the advantage of double is to "isolate" each test and test ONLY that particular thing you're wanting too. For example, if I have some problem on Gui class all 4 examples will fail, when you probably would want it to fail on ONLY one particular test, as the others don't rely on the actual object but rely on a double. Is it what you are willing to accomplish?

**Update** - discussed and now using doubles and let.

### CODE REVIEW

**Comment by abinoam** [comment]
Failed on travis https://travis-ci.org/mrhead/ruby_arena/builds/16124441

Working on it.

Probably, we should stub Gosu::Window ;-)

**Comment by abinoam** [comment]
It's not the most beatiful code of the world, but it's working.
I've had to fake Gosu::Window and reload Gui so that a new Gui class be created inheriting from this fake Gosu::Window.

Perhaps there's a more RSpec-ish way of doing it. 
But, as a beginner on RSpec, I could'nt figure it out.

**Comment by mrhead** [comment]
I've used RSpec also before, but this was first time I used doubles... The main reason is that I've read POODR (http://www.poodr.com/) and I wanted to test everything in isolation and do not introduce coupling in test. I think that doubles are great for this.

Only issue which I see is that doubles do no reflect real interface of objects...

But anyway I would like to see also other opinions from experienced guys.

**Comment by abinoam** [comment]
So let's break the problem into smaller parts.

1) For the "Gui" class we cannot inherite it from Gosu::Window (at the test time) because travis running in a console without an Window Manager loaded it will crash! So, even if we don't use this code we still need that FakeGui part of the code. Am I thinking/getting it right or not?

2) To test each part in isolation we should use the actual implementation of each one BUT doubling the other parts. Am I thinking/getting it right or not? So, at this spec we should use the ACTUAL Gui only with the other components being only doubles, is it this?

I'll be working on it and let me know if I'm not getting the point.

**Comment by abinoam** [comment]
This new commit does:
1. Revert to the "double" approach almost **exactly** the same way as master branch is by now. But, instead of using methods definitions that holds on instance variables (memoizes) the doubles created, I have used simple instance variables inside a before(:each) block. Creates the doubles for each example.
2. Use before(:each) instead of before(:all). Because of:
*\* http://makandracards.com/makandra/11507-using-before-all-in-rspec-will-cause-you-lots-of-trouble-unless-you-know-what-you-are-doing
*\* https://github.com/rspec/rspec-mocks#use-beforeeach-not-beforeall
3. Keep on using the FakeGui of previous commits. It's the only way I find (till now) to avoid travis crashing.

I think we can merge this and go on from here. 
But feel free to hold on if you want.

**Comment by mrhead** [comment]
@abinoam thanks for your work!

But is there any specific reason why you did not use `let(:gui) { FakeGui.new(arena) }`?

Previous approach with custom methods was just alternative to it. I just wanted to try it and there is simple advantage to `let` that you can also use method parameters if they are needed.

Also when using `let` or custom method object is created just when it is needed. For example with your setup you are creating `@robot` and `@bullet` in 'publict interface' tests even when they are not needed.

If you are not familiar with RSpec `let` method you can find more information here: https://www.relishapp.com/rspec/rspec-core/v/2-6/docs/helper-methods/let-and-let

I prefer custom methods or `let` more than `before(:each)...`. What do you think? Can you modify your code again?

Thanks!

**Comment by abinoam** [comment]
Check it out now. We are improving it well.

**Pull request merged**
